// this file is generated by cmake automatically, don't edit it.
#include <stdarg.h>
#include <stddef.h>
#include <setjmp.h>
#include <cmocka.h>

void ____run_finish____(void **state) { (void) state; }

// codegen here

int main(int argc, char *argv[]) {
    const struct CMUnitTest tests[] = {
        // codegen here
        cmocka_unit_test(____run_finish____)
    };
    return cmocka_run_group_tests(tests, NULL, NULL);
}
